[package]
name = "natives"
authors = ["GlennFolker"]
version = "1.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
jni = "0.21.0"

[package.metadata.android.sdk]
min_sdk_version = 14
target_sdk_version = 33
